-- Antonio
BEGIN
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Pedro Perez', DATE '2023-05-05', 'pedro@gmail.com', 'Grecia Centro', 79);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Juan Paez', DATE '2023-05-05', 'juan@gmail.com', 'Grecia Centro', 69);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Julio Asir', DATE '2023-05-07', 'julio@gmail.com', 'Grecia Centro', 89);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Vardimir Yusuf', DATE '2023-02-05', 'tusuf@gmail.com', 'Grecia Centro', 10);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Isaias Reque', DATE '2023-05-01', 'reque@gmail.com', 'Grecia Centro', 99);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Manuel Calderon', DATE '2023-03-05', 'manuel@gmail.com', 'Grecia Centro', 69);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Melvin Ramirez', DATE '2023-05-09', 'mel@gmail.com', 'Grecia Centro', 10);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Koky Saldo', DATE '2023-02-05', 'koky@gmail.com', 'Grecia Centro', 12);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Probabilidad Fernandez', DATE '2023-05-05', 'proba@gmail.com', 'Grecia Centro', 80);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Fundamentos Charpentier', DATE '2023-04-05', 'funda@gmail.com', 'Grecia Centro', 56);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Arquitectura Gomez', DATE '2023-05-08', 'arqui@gmail.com', 'Grecia Centro', 23);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Tzu Rue', DATE '2023-09-05', 'tzurue@gmail.com', 'Grecia Centro', 12);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Algebra Gonzales', DATE '2023-05-01', 'alge@gmail.com', 'Grecia Centro', 90);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Discreta Alvarez', DATE '2023-05-01', 'discreta@gmail.com', 'Grecia Centro', 67);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Volador Enriquez', DATE '2023-08-02', 'volador@gmail.com', 'Grecia Centro', 11);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Manrique Lopez', DATE '2023-01-01', 'manriquito@gmail.com', 'Grecia Centro', 78);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Kosta Latysh', DATE '2023-03-03', 'kosta@gmail.com', 'Grecia Centro', 12);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Yargen Humberto', DATE '2023-05-01', 'yargen@gmail.com', 'Grecia Centro', 44);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Leonardo Hulio', DATE '2023-02-02', 'leonardo@gmail.com', 'Grecia Centro', 90);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Erling Lopez', DATE '2023-02-05', 'erling@gmail.com', 'Grecia Centro', 290);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Manfred Messi', DATE '2023-05-01', 'godfred@gmail.com', 'Grecia Centro', 80);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Alejandro Ronaldo', DATE '2023-09-01', 'ale@gmail.com', 'Grecia Centro', 71);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Federico Roman', DATE '2023-05-09', 'fede@gmail.com', 'Grecia Centro', 123);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Julian Nuñez', DATE '2023-02-08', 'julia@gmail.com', 'Grecia Centro', 6);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Maria Messi', DATE '2023-01-05', 'maria@gmail.com', 'Grecia Centro', 100);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Danna Porras', DATE '2023-05-01', 'danna@gmail.com', 'Grecia Centro', 12);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Bad Bunny', DATE '2023-03-05', 'chambea@gmail.com', 'Grecia Centro', 90);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Juan Balvin', DATE '2023-02-05', 'jbalvin@gmail.com', 'Grecia Centro', 4);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Maluma Baby', DATE '2023-02-09', 'maluma@gmail.com', 'Grecia Centro', 69);
    INSERT INTO CLIENTE VALUES (seq_cliente.NEXTVAL, 'Maripaz Cespedes', DATE '2023-02-05', 'koky@gmail.com', 'Grecia Centro', 55);

    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Quesos Rubi', 'Trae quesos', 'Alajuela centro');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Carnes San Jose', 'Trae carnes', 'San Jose centro');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Electronicos Luisito', 'Trae aparatos electronicos', 'Grecia, Alajuela');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Papas El carton', 'Proveedor de papas', 'Grecia, Alajuela');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Carnes San Carlos', 'Trae carnes de San Carlos', 'San Carlos, Alajuela');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Leche San Osito', 'Trae lacteos', 'Cartago centro');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Arroces el Burro', 'Proveedor de arroz', 'Puntarenas centro');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Frijolera Ruiz', 'Proveedor de frijoles', 'San Ramon, Alajuela');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Mantequillas San Humberto', 'Trae mantequillas', 'Barva, Heredia');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Tortillera El maicito', 'Proveedor de tortillas', 'San Carlos, Alajuela');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Especias Marito', 'Proveedor de especias', 'San Jose centro');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Filtros el Hugo', 'Trae filtros para cafeteras', 'Guanacaste');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Chapstick Life', 'Proveedor de chapsticks', 'Alajuela, centro');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Lapiceros Manuelito', 'Proveedor de lapiceros', 'Escazú, San José');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Fundas CeluWorld', 'Proveedor de fundas para telefono', 'Heredia centro');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Frescos La hortaliza', 'Trae refescos variados', 'San Carlos, Alajuela');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Cafes el grano', 'Proveedor de cafes', 'San Jose centro');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Cafes el Cafe', 'Proveedor de cafes', 'Pavas, San José');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Grapas el grapon', 'Proveedor de grapas', 'San Jose centro');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Borradores Lucho', 'Proveedor de borradores', 'Santo Domingo, Heredia');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Paquetillos el enamorado', 'Proveedor de de tostadospaquetillos ', 'San Luis, Grecia');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Caramelos el dulce', 'Proveedor de caramelos', 'San Jose centro');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Confites el Ruso', 'Proveedor de confites rusos', 'San Jose centro');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Porcelana la Porcelana fina', 'Proveedor de porcelana', 'Leon 13');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Relojes el Reoljito', 'Proveedor de relojes', 'San Ramon, Alajuela');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Yucas la Fortuna', 'Proveedor de caramelos', 'La fortuna');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Paperia las papitas', 'Proveedor de papas', 'Cartago');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Carnes la Chuleteria', 'Trae chuketas', 'San Jose centro');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'Pipo Pages', 'Trae hojas', 'San Jose centro');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'El manjar del perro', 'Trae comida de perros', 'Grecia, Alajuela');
    INSERT INTO PROVEEDOR VALUES (seq_proveedor.NEXTVAL, 'El manjar del gato', 'Trae comida de gatos', 'San Jose centro');

    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-12-25', 1);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-05-27', 2);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-07-03', 3);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-10-17', 4);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-10-16', 5);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-08-26', 6);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-10-23', 7);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-11-13', 8);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-02-03', 9);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-03-29', 10);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-11-30', 11);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-05-15', 12);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-01-31', 13);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-01-30', 14);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-08-26', 15);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-12-11', 16);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-12-23', 17);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-06-16', 18);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-01-13', 19);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-07-27', 20);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-06-09', 21);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-04-20', 22);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-06-27', 23);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-10-30', 24);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-04-12', 25);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-06-20', 26);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-03-25', 27);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-04-30', 28);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-10-14', 29);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-09-09', 30);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-07-09', 1);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-04-01', 2);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-08-18', 3);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-05-25', 4);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-09-18', 5);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-12-08', 6);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-01-26', 7);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-08-18', 8);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-07-17', 9);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-05-30', 10);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-04-09', 11);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-05-11', 12);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-05-16', 13);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-03-15', 14);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-11-29', 15);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-10-11', 16);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-05-29', 17);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-10-08', 18);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-07-05', 19);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-07-31', 20);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-05-31', 21);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-05-22', 22);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-09-20', 23);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-03-25', 24);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-01-05', 25);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-08-30', 26);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-08-06', 27);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-12-12', 28);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-01-09', 29);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-07-28', 30);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-12-21', 1);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-08-15', 2);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-08-07', 3);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-06-14', 4);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-12-11', 5);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-07-17', 6);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-05-05', 7);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-08-26', 8);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-09-02', 9);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-04-06', 10);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-04-22', 11);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-08-11', 12);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-01-12', 13);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-08-04', 14);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-05-17', 15);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-11-03', 16);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-12-07', 17);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-10-12', 18);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-06-24', 19);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-03-13', 20);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-10-17', 21);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-10-20', 22);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-09-24', 23);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-07-17', 24);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-10-19', 25);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-05-02', 26);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-08-07', 27);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-09-01', 28);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-07-25', 29);
    INSERT INTO RECIBO VALUES (seq_recibo.NEXTVAL, DATE '2023-10-05', 30);


    -- Josué
    --Categorías

    INSERT INTO CATEGORIA  VALUES ('Electrónica', 'Productos electrónicos para el consumo diario.'); 
    INSERT INTO CATEGORIA  VALUES ('Ropa', 'Ropa y accesorios de moda para hombres y mujeres.');
    INSERT INTO CATEGORIA  VALUES ('Calzado', 'Calzado de diversos estilos y tallas.');
    INSERT INTO CATEGORIA  VALUES ('Electrodomésticos', 'Electrodomésticos para el hogar');
    INSERT INTO CATEGORIA  VALUES ('Joyería', 'Joyas y bisutería');
    INSERT INTO CATEGORIA  VALUES ('Muebles', 'Muebles y decoración para el hogar.');
    INSERT INTO CATEGORIA  VALUES ('Productos de Belleza', 'Productos de cuidado personal y belleza.');
    INSERT INTO CATEGORIA  VALUES ('Juguetes', 'Juguetes para niños.');
    INSERT INTO CATEGORIA  VALUES ('Librería', 'Productos para estudio u oficina.');
    INSERT INTO CATEGORIA  VALUES ('Deportivo', 'Artículos para deporte');
    INSERT INTO CATEGORIA  VALUES ('Carnes', 'Productos hechos de carne');
    INSERT INTO CATEGORIA  VALUES ('Bebés', 'Productos para bebés y cuidado infantil.');
    INSERT INTO CATEGORIA  VALUES ('Bebidas', 'Productos que se consumen tomandolo');
    INSERT INTO CATEGORIA  VALUES ('Ferretería', 'Herramientas y suministros de ferretería.');
    INSERT INTO CATEGORIA  VALUES ('Mariscos', 'Productos provenientes del mar');
    INSERT INTO CATEGORIA  VALUES ('Limpieza', 'Productos de limpieza');
    INSERT INTO CATEGORIA  VALUES ('Snacks', 'Productos para picar');
    INSERT INTO CATEGORIA  VALUES ('Jardinería', 'Suministros y herramientas para jardinería.');
    INSERT INTO CATEGORIA  VALUES ('Mascotas', 'Suministros y alimentos para mascotas.');
    INSERT INTO CATEGORIA  VALUES ('Congelados', 'Productos congelados');
    INSERT INTO CATEGORIA  VALUES ('Instrumentos Musicales', 'Instrumentos musicales y accesorios.');
    INSERT INTO CATEGORIA  VALUES ('Sexo', 'Productos relacionado al coito');
    INSERT INTO CATEGORIA  VALUES ('Cocina', 'Utensilios y productos para cocina.');
    INSERT INTO CATEGORIA  VALUES ('Dulces', 'Confites, chocolates, etc...');
    INSERT INTO CATEGORIA  VALUES ('Fiesta', 'Suministros para fiestas y eventos especiales.');
    INSERT INTO CATEGORIA  VALUES ('Embutidos', 'Productos embutidos');
    INSERT INTO CATEGORIA  VALUES ('Frutas', 'Frutas para la familia');
    INSERT INTO CATEGORIA  VALUES ('Vegetales', 'Verduras para la familia');
    INSERT INTO CATEGORIA  VALUES ('Enlatados', 'Productos que vienen en una lata');
    INSERT INTO CATEGORIA  VALUES ('Lácteos', 'Productos provenientes de la leche');

    -- Productos


    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Samsung 78', 'Teléfono móvil inteligente', 250000 , 'Electrónica', 15);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Vestido Shein', 'Elegante vestido de noche', 15000, 'Ropa', 32);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Naik', 'Calzado deportivo para correr y hacer ejercicio', 35000, 'Calzado', 5);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Refrigerador Samsung', 'Refrigerador de gran capacidad', 650000, 'Electrodomésticos', 3);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Anillo de plata', 'Anillo con plata de alta calidad', 80000, 'Joyería', 2);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Sofá', 'Sofá de cuero de lujo', 350000, 'Muebles', 1);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Crema Hidratante', 'Crema hidratante para el cuidado de la piel', 13000, 'Productos de Belleza', 67);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Blocks', 'Set de construcción de bloques para niños', 10000, 'Juguetes', 43);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Cuaderno de Notas', 'Cuaderno de notas para tomar apuntes', 3000, 'Librería', 13);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Balón de Fútbol', 'Balón de fútbol oficial', 20000, 'Deportivo', 17);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Filete de Res', 'Filete de res de primera calidad', 2000, 'Carnes', 120);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Pañales para Bebés', 'Pañales desechables para bebés', 24000, 'Bebés', 23);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Vino Tinto', 'Botella de vino tinto de alta calidad', 50000, 'Bebidas', 20);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Martillo', 'Herramienta para clavar', 7000, 'Ferretería', 100);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Camarones Frescos', 'Camarones frescos para cocinar', 16000, 'Mariscos', 30);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Detergente Líquido', 'Detergente líquido para lavar ropa', 5000, 'Limpieza', 14);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Papiola', 'Chips de papas crujientes y sabrosos', 300, 'Snacks', 300);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Tijeras', 'Tijeras para jardín', 4500, 'Jardinería', 12);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Alimento para Gatos', 'Alimento de alta calidad para gatos', 3600, 'Mascotas', 25);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Pizza Congelada', 'Pizza congelada para una cena rápida', 3000, 'Congelados', 60);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Flauta', 'Flauta para músicos aficionados', 15000, 'Instrumentos Musicales', 15);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Condones', 'Condones de calidad para la protección', 2500, 'Sexo', 200);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Cuchillo', 'Cuchillo para cocinar', 5500, 'Cocina', 40);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Barra de Chocolate', 'Barra de chocolate suizo premium', 1500, 'Dulces', 25);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Globos', 'Globos para fiestas', 2500, 'Fiesta', 26);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Salchichas Ahumadas', 'Salchichas ahumadas para parrilladas', 4500, 'Embutidos', 50);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Manzanas', 'Manzanas frescas y crujientes', 1000, 'Frutas', 200);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Zanahorias', 'Zanahorias orgánicas', 1250, 'Vegetales', 96);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Atún', 'Atún de agua', 400, 'Enlatados', 56);
    INSERT INTO PRODUCTO VALUES (seq_producto.NEXTVAL, 'Leche Entera', 'Leche entera fresca y nutritiva', 1700, 'Lácteos', 80);

    INSERT INTO USUARIO(nombre, passhash1, passhash2, nivel) VALUES('admin', 133524947, 894447882, 1);

    INSERT INTO PRODUCTO_RECIBO VALUES (1, 1, 38);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 1, 1000, 38, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (2, 2, 24);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 2, 1000, 24, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (3, 3, 21);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 3, 1000, 21, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (4, 4, 40);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 4, 1000, 40, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (5, 5, 43);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 5, 1000, 43, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (6, 6, 12);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 6, 1000, 12, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (7, 7, 42);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 7, 1000, 42, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (8, 8, 38);INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 8, 1000, 38, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (9, 9, 10);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 9, 1000, 10, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (10, 10, 27);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 10, 1000, 27, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (11, 11, 48);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 11, 1000, 48, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (12, 12, 3);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 12, 1000, 3, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (13, 13, 18);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 13, 1000, 18, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (14, 14, 40);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 14, 1000, 40, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (15, 15, 49);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 15, 1000, 49, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (16, 16, 3);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 16, 1000, 3, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (17, 17, 15);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 17, 1000, 15, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (18, 18, 14);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 18, 1000, 14, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (19, 19, 30);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 19, 1000, 30, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (20, 20, 23);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 20, 1000, 23, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (21, 21, 5);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 21, 1000, 5, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (22, 22, 3);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 22, 1000, 3, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (23, 23, 27);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 23, 1000, 27, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (24, 24, 40);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 24, 1000, 40, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (25, 25, 17);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 25, 1000, 17, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (26, 26, 10);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 26, 1000, 10, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (27, 27, 14);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 27, 1000, 14, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (28, 28, 30);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 28, 1000, 30, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (29, 29, 2);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 29, 1000, 2, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (30, 30, 11);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 30, 1000, 11, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (1, 2, 6);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 1, 1000, 6, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (2, 3, 33);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 2, 1000, 33, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (3, 4, 39);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 3, 1000, 39, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (4, 5, 13);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 4, 1000, 13, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (5, 6, 40);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 5, 1000, 40, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (6, 7, 29);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 6, 1000, 29, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (7, 8, 5);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 7, 1000, 5, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (8, 9, 25);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 8, 1000, 25, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (9, 10, 3);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 9, 1000, 3, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (10, 11, 16);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 10, 1000, 16, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (11, 12, 5);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 11, 1000, 5, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (12, 13, 4);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 12, 1000, 4, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (13, 14, 26);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 13, 1000, 26, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (14, 15, 42);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 14, 1000, 42, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (15, 16, 27);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 15, 1000, 27, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (16, 17, 41);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 16, 1000, 41, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (17, 18, 30);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 17, 1000, 30, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (18, 19, 17);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 18, 1000, 17, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (19, 20, 42);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 19, 1000, 42, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (20, 21, 13);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 20, 1000, 13, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (21, 22, 9);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 21, 1000, 9, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (22, 23, 16);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 22, 1000, 16, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (23, 24, 35);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 23, 1000, 35, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (24, 25, 46);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 24, 1000, 46, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (25, 26, 26);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 25, 1000, 26, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (26, 27, 26);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 26, 1000, 26, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (27, 28, 22);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 27, 1000, 22, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (28, 29, 42);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 28, 1000, 42, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (29, 30, 30);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 29, 1000, 30, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (30, 1, 18);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 30, 1000, 18, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (1, 3, 4);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 1, 1000, 4, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (2, 4, 28);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 2, 1000, 28, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (3, 5, 44);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 3, 1000, 44, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (4, 6, 37);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 4, 1000, 37, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (5, 7, 29);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 5, 1000, 29, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (6, 8, 42);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 6, 1000, 42, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (7, 9, 49);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 7, 1000, 49, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (8, 10, 38);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 8, 1000, 38, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (9, 11, 46);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 9, 1000, 46, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (10, 12, 27);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 10, 1000, 27, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (11, 13, 31);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 11, 1000, 31, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (12, 14, 42);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 12, 1000, 42, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (13, 15, 48);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 13, 1000, 48, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (14, 16, 9);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 14, 1000, 9, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (15, 17, 50);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 15, 1000, 50, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (16, 18, 30);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 16, 1000, 30, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (17, 19, 36);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 17, 1000, 36, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (18, 20, 29);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 18, 1000, 29, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (19, 21, 29);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 19, 1000, 29, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (20, 22, 22);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 20, 1000, 22, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (21, 23, 30);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 21, 1000, 30, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (22, 24, 28);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 22, 1000, 28, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (23, 25, 28);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 23, 1000, 28, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (24, 26, 49);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 24, 1000, 49, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (25, 27, 22);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 25, 1000, 22, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (26, 28, 31);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 26, 1000, 31, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (27, 29, 4);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 27, 1000, 4, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (28, 30, 50);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 28, 1000, 50, 'efectivo', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (29, 1, 36);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 29, 1000, 36, 'credito', 'Wikir wokir wakar');
    INSERT INTO PRODUCTO_RECIBO VALUES (30, 2, 31);
    INSERT INTO RECIBO_DETALLE VALUES (seq_recibo_detalle.NEXTVAL, 30, 1000, 31, 'efectivo', 'Wikir wokir wakar');

    -- Compra producto

    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,1,1,DATE '2023-02-09');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,1,1,DATE '2023-02-10');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,1,1,DATE '2023-05-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,2,2,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,2,2,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,2,2,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,3,3,DATE '2023-05-09');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,3,3,DATE '2023-05-10');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,3,3,DATE '2023-05-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,4,4,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,4,4,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,4,4,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,5,5,DATE '2023-05-09');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,5,5,DATE '2023-05-10');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,5,5,DATE '2023-05-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,6,6,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,6,6,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,6,6,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,7,7,DATE '2023-05-09');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,7,7,DATE '2023-05-10');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,7,7,DATE '2023-05-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,8,8,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,8,8,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,8,8,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,9,9,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,9,9,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,9,9,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,10,10,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,10,10,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,10,10,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,11,11,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,11,11,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,11,11,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,12,12,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,12,12,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,12,12,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,13,13,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,13,13,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,13,13,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,14,14,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,14,14,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,14,14,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,15,15,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,15,15,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,15,15,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,16,16,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,16,16,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,16,16,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,17,17,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,17,17,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,17,17,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,18,18,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,18,18,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,18,18,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,19,19,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,19,19,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,19,19,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,20,20,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,20,20,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,20,20,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,21,21,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,21,21,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,21,21,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,22,22,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,22,22,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,22,22,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,23,23,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,23,23,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,23,23,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,24,24,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,24,24,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,24,24,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,25,25,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,25,25,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,25,25,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,26,26,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,26,26,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,26,26,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,27,27,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,27,27,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,27,27,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,28,28,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,28,28,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,28,28,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,29,29,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,29,29,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,29,29,DATE '2023-08-11');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,30,30,DATE '2023-05-12');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,30,30,DATE '2023-07-13');
    INSERT INTO COMPRA_PRODUCTO VALUES(seq_compra_producto.NEXTVAL,30,30,DATE '2023-08-11');

    -- Compra detalle

    
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 1, 10, 2000, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 2, 15, 3000, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 3, 8, 1600, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 4, 12, 2400, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 5, 6, 1200, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 6, 20, 4000, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 7, 4, 800, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 8, 18, 3600, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 9, 10, 2000, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 10, 5, 1000, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 11, 7, 1400, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 12, 9, 1800, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 13, 3, 600, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 14, 14, 2800, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 15, 11, 2200, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 16, 2, 400, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 17, 5, 1000, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 18, 8, 1600, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 19, 16, 3200, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 20, 6, 1200, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 21, 3, 600, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 22, 12, 2400, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 23, 9, 1800, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 24, 4, 800, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 25, 7, 1400, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 26, 13, 2600, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 27, 8, 1600, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 28, 5, 1000, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 29, 9, 1800, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 30, 11, 2200, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 1, 10, 2000, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 2, 15, 3000, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 3, 8, 1600, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 4, 12, 2400, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 5, 6, 1200, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 6, 20, 4000, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 7, 4, 800, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 8, 18, 3600, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 9, 10, 2000, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 10, 5, 1000, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 11, 7, 1400, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 12, 9, 1800, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 13, 3, 600, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 14, 14, 2800, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 15, 11, 2200, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 16, 2, 400, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 17, 5, 1000, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 18, 8, 1600, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 19, 16, 3200, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 20, 6, 1200, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 21, 3, 600, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 22, 12, 2400, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 23, 9, 1800, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 24, 4, 800, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 25, 7, 1400, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 26, 13, 2600, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 27, 8, 1600, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 28, 5, 1000, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 29, 9, 1800, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 30, 11, 2200, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 1, 10, 2000, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 2, 15, 3000, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 3, 8, 1600, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 4, 12, 2400, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 5, 6, 1200, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 6, 20, 4000, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 7, 4, 800, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 8, 18, 3600, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 9, 10, 2000, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 10, 5, 1000, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 11, 7, 1400, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 12, 9, 1800, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 13, 3, 600, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 14, 14, 2800, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 15, 11, 2200, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 16, 2, 400, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 17, 5, 1000, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 18, 8, 1600, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 19, 16, 3200, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 20, 6, 1200, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 21, 3, 600, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 22, 12, 2400, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 23, 9, 1800, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 24, 4, 800, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 25, 7, 1400, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 26, 13, 2600, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 27, 8, 1600, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 28, 5, 1000, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 29, 9, 1800, 'Productos variados');
    INSERT INTO COMPRA_DETALLE  VALUES (seq_compra_detalle.NEXTVAL, 30, 11, 2200, 'Productos variados');

    COMMIT;
END;